#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "silverbullet"
name = "SilverBullet"
description.en = "Creative space where you collect, create and expand your personal knowledge"
description.fr = "Espace créatif où vous recueillez, créez et élargissez vos connaissances personnelles"

version = "0.9.2~ynh2"

maintainers = ["fflorent"]

[upstream]
license = "MIT"
website = "https://silverbullet.md"
demo = "https://play.silverbullet.md/"
code = "https://github.com/silverbulletmd/silverbullet"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = [ "amd64", "arm64" ]
multi_instance = true

ldap = false

sso = false

disk = "100M"
ram.build = "50M"
ram.runtime = "250M"

[install]
    [install.domain]
    type = "domain"

    [install.admin]
    help.en = "Choose the user who can access to silverbullet"
    help.fr = "Choisissez l'utilisateur pouvant accéder à silverbullet"
    type = "user"

[resources]

    [resources.sources]

    [resources.sources.main]
    in_subdir=false
    amd64.url = "https://github.com/silverbulletmd/silverbullet/releases/download/0.9.2/silverbullet-server-linux-x86_64.zip"
    amd64.sha256 = "378d755a6ddbbbc9ae3b557e0d54beae08269147bda85ab2e13b77f9e5349d15"
    arm64.url = "https://github.com/silverbulletmd/silverbullet/releases/download/0.9.2/silverbullet-server-linux-aarch64.zip"
    arm64.sha256 = "f93b1fc42e552b38c5b48ce85c5f69afaa994653edabf59f3468c6130cce5f42"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset.amd64 = "^silverbullet-server-linux-x86_64.zip$"
    autoupdate.asset.arm64 = "^silverbullet-server-linux-aarch64.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "notes" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
