#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "silverbullet"
name = "SilverBullet"
description.en = "a creative space where you collect, create and expand your personal knowledge"
description.fr = "un espace créatif où vous recueillez, créez et élargissez vos connaissances personnelles"

version = "0.8.1~ynh1"

maintainers = ["fflorent"]

[upstream]
license = "MIT"
website = "https://silverbullet.md"
demo = "https://play.silverbullet.md/"
code = "https://github.com/silverbulletmd/silverbullet"

[integration]
yunohost = ">= 11.2"
architectures = [ "amd64" ]
multi_instance = true

ldap = false

sso = false

disk = "100M"
ram.build = "50M"
ram.runtime = "250M"

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "domain"

    [install.admin]
    help.en = "Choose the user who can access to silverbullet"
    help.fr = "Choisissez l'utilisateur pouvant accéder à silverbullet"
    type = "user"

[resources]
    # See the packaging documentation for the full set
    # of explanation regarding the behavior and properties for each of those

    [resources.sources]

    [resources.sources.main]
    in_subdir=false
    url = "https://github.com/silverbulletmd/silverbullet/releases/download/0.8.1/silverbullet-server-linux-x86_64.zip"
    sha256 = "84a27dc7ec09183b67da58a9cbe783d17747029b031c980135e40cabe7392971"
    autoupdate.strategy = "latest_github_release"
    autoupdate.asset = "^silverbullet-server-linux-x86_64.zip$"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = [ "notes" ]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
